<a href="https://colab.research.google.com/github/yohanesnuwara/reservoir-geomechanics/blob/master/unconve/homework%202/homework2_unconve_geomechanics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Homework 2. Composition, Elasticity and Ductility**

In [0]:
import numpy as np
import matplotlib.pyplot as plt

## Part 1. Composition, microstructure, and elastic properties


### A. Determine the percentage by weight of each components (clay + TOC, QFP, carbonates) from ternary diagram

Rule of reading ternary see [here](http://csmgeo.csm.jmu.edu/geollab/fichter/SedRx/readternary.html)

![ternary-diagram-hw2](https://user-images.githubusercontent.com/51282928/79852721-3c491180-83f1-11ea-9493-a05fcc0e6492.PNG)

In [0]:
# Barnett
barnett_clay = 0.55
barnett_carb = 0.05
barnett_qfp = 0.4

# Eagle Ford
eagle_clay = 0.2
eagle_carb = 0.65
eagle_qfp = 0.15

### B. Estimate the density for each sample. 

In [0]:
# mineral densities and modulus (GPa and g/cc)
K_qtz = 37; G_qtz = 44; rho_qtz = 2.65
K_carb = 70.2; G_carb = 29; rho_carb = 2.71
K_clay = 8.5; G_clay = 4.5; rho_clay = 1.95

# barnett
rho_barnett = (barnett_clay * rho_clay) + (barnett_carb * rho_carb) + (barnett_qfp * rho_qtz)
rho_eagle = (eagle_clay * rho_clay) + (eagle_carb * rho_carb) + (eagle_qfp * rho_qtz)

print('Estimated density of Barnett 45H sample:', rho_barnett, 'g/cc')
print('Estimated density of Eagle Ford 65H sample:', rho_eagle, 'g/cc')

Estimated density of Barnett 45H sample: 2.268 g/cc
Estimated density of Eagle Ford 65H sample: 2.549 g/cc


### C. Calculate elastic moduli from ultrasonic measurements

$$V_s = \sqrt{\frac{G}{\rho}}$$

$$V_p = \sqrt{\frac{K+\frac{4}{3}G}{\rho}}$$

Rearranging gives:

$$\rho V_s^2 = G$$

$$\rho V_p^2 -\frac{4}{3}G= K$$

In [0]:
Vp_eagle = 6000 # m/s
Vp_barnett = 5000
Vs_eagle = 3300 
Vs_barnett = 3200

G_barnett = (rho_barnett * 1000) * (Vs_barnett**2) * 1E-09 # convert density from g/cc to kg/m3
K_barnett = ((rho_barnett * 1000) * (Vp_barnett**2) * 1E-09) - ((4/3) * G_barnett)
G_eagle = (rho_eagle * 1000) * (Vs_eagle**2) * 1E-09 
K_eagle = ((rho_eagle * 1000) * (Vp_eagle**2) * 1E-09) - ((4/3) * G_eagle)


print('Shear modulus of Barnett 45H sample from ultrasonic measurement:', G_barnett, 'GPa')
print('Bulk modulus of Barnett 45H sample from ultrasonic measurement:', K_barnett, 'GPa')
print('Shear modulus of Eagle Ford 65H sample from ultrasonic measurement:', G_eagle, 'GPa')
print('Bulk modulus of Eagle Ford 65H sample from ultrasonic measurement:', K_eagle, 'GPa')

Shear modulus of Barnett 45H sample from ultrasonic measurement: 23.224320000000002 GPa
Bulk modulus of Barnett 45H sample from ultrasonic measurement: 25.73424 GPa
Shear modulus of Eagle Ford 65H sample from ultrasonic measurement: 27.75861 GPa
Bulk modulus of Eagle Ford 65H sample from ultrasonic measurement: 54.75252000000001 GPa


## D. Calculate eﬀective elastic moduli using Iso-Stress and Iso-Strain Averaging

Iso-stress method (Reuss geometric averaging):

$$\frac{1}{M_R} = \sum_{i=1}^{N} \frac{f_i}{M_i}$$

Iso-strain method (Reuss geometric averaging):

$$M_V = \sum_{i=1}^{N} f_iM_i$$

In [0]:
barnett_composition = np.array([barnett_clay, barnett_carb, barnett_qfp])
eagle_composition = np.array([eagle_clay, eagle_carb, barnett_qfp])

Km = np.array([K_clay, K_carb, K_qtz]) # mineral bulk modulus
Gm = np.array([G_clay, G_carb, G_qtz]) # mineral shear modulus

# iso-stress (reuss lower bound of modulus)
Km_inv = 1 / Km; Gm_inv = 1 / Gm

Kr_barnett = 1 / (np.sum(barnett_composition * Km_inv))
Kr_eagle = 1 / (np.sum(eagle_composition * Km_inv))
Gr_barnett = 1 / (np.sum(barnett_composition * Gm_inv))
Gr_eagle = 1 / (np.sum(eagle_composition * Gm_inv))

# iso-strain (voigt upper bound of modulus)
Kv_barnett = (np.sum(barnett_composition * Km))
Kv_eagle = (np.sum(eagle_composition * Km))
Gv_barnett = (np.sum(barnett_composition * Gm))
Gv_eagle = (np.sum(eagle_composition * Gm))

print('Reuss lower bound (iso-stress) bulk modulus of Barnett 45H:', Kr_barnett, 'GPa')
print('Reuss lower bound (iso-stress) shear modulus of Barnett 45H:', Gr_barnett, 'GPa')
print('Voigt upper bound (iso-strain) bulk modulus of Barnett 45H:', Kv_barnett, 'GPa')
print('Voigt upper bound (iso-strain) shear modulus of Barnett 45H:', Gv_barnett, 'GPa \n')

print('Reuss lower bound (iso-stress) bulk modulus of Eagle Ford 65H:', Kr_eagle, 'GPa')
print('Reuss lower bound (iso-stress) shear modulus of Eagle Ford 65H:', Gr_eagle, 'GPa')
print('Voigt upper bound (iso-strain) bulk modulus of Eagle Ford 65H:', Kv_eagle, 'GPa')
print('Voigt upper bound (iso-strain) shear modulus of Eagle Ford 65H:', Gv_eagle, 'GPa')

Reuss lower bound (iso-stress) bulk modulus of Barnett 45H: 13.118376684145634 GPa
Reuss lower bound (iso-stress) shear modulus of Barnett 45H: 7.51669066631758 GPa
Voigt upper bound (iso-strain) bulk modulus of Barnett 45H: 22.985 GPa
Voigt upper bound (iso-strain) shear modulus of Barnett 45H: 21.525000000000002 GPa 

Reuss lower bound (iso-stress) bulk modulus of Eagle Ford 65H: 22.936052400567224 GPa
Reuss lower bound (iso-stress) shear modulus of Eagle Ford 65H: 13.166704884200872 GPa
Voigt upper bound (iso-strain) bulk modulus of Eagle Ford 65H: 62.13000000000001 GPa
Voigt upper bound (iso-strain) shear modulus of Eagle Ford 65H: 37.35 GPa


## Part 2.  Hydraulic fracture propagation in layered media

### A, B. Calculate net pressure for each layer for 3 ft fracture propagation

$$P-S3=\frac{C}{\pi \sqrt{L}}$$

Where $(P-S3)$ is net pressure, $K_{IC}$ is the critical stress intensity factor for mode I cracks (KIC), and $L$ is fracture length. 

![net-pressure-hydraulic](https://user-images.githubusercontent.com/51282928/80018511-4efe3c00-8500-11ea-9b13-c03f02c7bc8c.PNG)

In [0]:
# minimum horizontal stress of each layer
Sh1 = 5150; Sh2 = 4500; Sh3 = 5000; Sh4 = 5050; Sh5 = 6200

# critical stress intensity factor for mode I cracks (KIC), psi/sqrt(ft)
KIC1 = 500; KIC2 = 300; KIC3 = 600; KIC4 = 200; KIC5 = 400

Sh = np.array([Sh1, Sh2, Sh3, Sh4, Sh5])
KIC = np.array([KIC1, KIC2, KIC3, KIC4, KIC5])

length1 = 3 # fracture length to be propagated, ft

netpressure = KIC / (np.pi * np.sqrt(length1))

netpressure1_3ft = netpressure[0]
netpressure2_3ft = netpressure[1]
netpressure3_3ft = netpressure[2]
netpressure4_3ft = netpressure[3]
netpressure5_3ft = netpressure[4]

print('Net pressure for 3 ft fracture propagation in layer 1:', netpressure1_3ft, 'psi')
print('Net pressure for 3 ft fracture propagation in layer 2:', netpressure2_3ft, 'psi')
print('Net pressure for 3 ft fracture propagation in layer 3:', netpressure3_3ft, 'psi')
print('Net pressure for 3 ft fracture propagation in layer 4:', netpressure4_3ft, 'psi')
print('Net pressure for 3 ft fracture propagation in layer 5:', netpressure5_3ft, 'psi')

Net pressure for 3 ft fracture propagation in layer 1: 91.88814923696535 psi
Net pressure for 3 ft fracture propagation in layer 2: 55.13288954217921 psi
Net pressure for 3 ft fracture propagation in layer 3: 110.26577908435841 psi
Net pressure for 3 ft fracture propagation in layer 4: 36.75525969478614 psi
Net pressure for 3 ft fracture propagation in layer 5: 73.51051938957228 psi


### C. Calculate net pressure for each layer for 1 ft fracture propagation

In [0]:
length2 = 1 # fracture length to be propagated, ft

netpressure = KIC / (np.pi * np.sqrt(length2))

netpressure1_1ft = netpressure[0]
netpressure2_1ft = netpressure[1]
netpressure3_1ft = netpressure[2]
netpressure4_1ft = netpressure[3]
netpressure5_1ft = netpressure[4]

print('Net pressure for 1 ft fracture propagation in layer 1:', netpressure1_1ft, 'psi')
print('Net pressure for 1 ft fracture propagation in layer 2:', netpressure2_1ft, 'psi')
print('Net pressure for 1 ft fracture propagation in layer 3:', netpressure3_1ft, 'psi')
print('Net pressure for 1 ft fracture propagation in layer 4:', netpressure4_1ft, 'psi')
print('Net pressure for 1 ft fracture propagation in layer 5:', netpressure5_1ft, 'psi')

Net pressure for 1 ft fracture propagation in layer 1: 159.15494309189535 psi
Net pressure for 1 ft fracture propagation in layer 2: 95.4929658551372 psi
Net pressure for 1 ft fracture propagation in layer 3: 190.9859317102744 psi
Net pressure for 1 ft fracture propagation in layer 4: 63.66197723675813 psi
Net pressure for 1 ft fracture propagation in layer 5: 127.32395447351627 psi


## Questions

### Q1

#### What is wt% of carbonates in Eagle Ford 65H? Enter the number as a percentage (e.g., 90)

In [0]:
print('Carbonate percentage in Eagle Ford 65H:', eagle_carb * 100, '%')

Carbonate percentage in Eagle Ford 65H: 65.0 %


#### What is wt% of QFP in Barnett 25H?

In [0]:
print('Quartz-Feldspar-Pyrite percentage in Barnett 25H:', barnett_qfp * 100, '%')

Quartz-Feldspar-Pyrite percentage in Barnett 25H: 40.0 %


#### What is wt% of clay + TOC in Barnett 25H?

In [0]:
print('Clay+Kerogen percentage in Barnett 25H:', barnett_clay * 100, '%')

Clay+Kerogen percentage in Barnett 25H: 55.00000000000001 %


### Q2

#### What is the density of Eagle Ford 65H in g/cc?

In [0]:
print('Estimated density of Eagle Ford 65H sample:', rho_eagle, 'g/cc')

Estimated density of Eagle Ford 65H sample: 2.549 g/cc


#### What is the density of Barnett 25H in g/cc?

In [0]:
print('Estimated density of Barnett 45H sample:', rho_barnett, 'g/cc')

Estimated density of Barnett 45H sample: 2.268 g/cc


### Q3

#### What is the bulk modulus of Eagle Ford 65H? Enter your answer in GPa.

In [0]:
print('Bulk modulus of Eagle Ford 65H sample from ultrasonic measurement:', K_eagle, 'GPa')

Bulk modulus of Eagle Ford 65H sample from ultrasonic measurement: 54.75252000000001 GPa


#### What is the shear modulus of Eagle Ford 65H? Enter your answer in GPa.

In [0]:
print('Shear modulus of Eagle Ford 65H sample from ultrasonic measurement:', G_eagle, 'GPa')

Shear modulus of Eagle Ford 65H sample from ultrasonic measurement: 27.75861 GPa


#### What is the bulk modulus of Barnett 25H? Enter your answer in GPa.

In [0]:
print('Bulk modulus of Barnett 25H sample from ultrasonic measurement:', K_barnett, 'GPa')

Bulk modulus of Barnett 25H sample from ultrasonic measurement: 25.73424 GPa


#### What is the shear modulus of Barnett 25H? Enter your answer in GPa.

In [0]:
print('Shear modulus of Barnett 25H sample from ultrasonic measurement:', G_barnett, 'GPa')

Shear modulus of Barnett 25H sample from ultrasonic measurement: 23.224320000000002 GPa


### Q4

#### What is the iso-strain bulk modulus of Barnett 25H? Enter your answer in GPa.

In [0]:
print('Voigt upper bound (iso-strain) bulk modulus of Barnett 45H:', Kv_barnett, 'GPa')

Voigt upper bound (iso-strain) bulk modulus of Barnett 45H: 22.985 GPa


#### What is the iso-stress bulk modulus of Barnett 25H? Enter your answer in GPa.

In [0]:
print('Reuss lower bound (iso-stress) bulk modulus of Barnett 45H:', Kr_barnett, 'GPa')

Reuss lower bound (iso-stress) bulk modulus of Barnett 45H: 13.118376684145634 GPa


#### Using the calculated values in Part 1d, what endmember condition do the ultrasonic velocity measurements represent?

Check which end member (iso-strain/iso-stress) is nearer to the calculated effective modulus from ultrasonic measurement

In [0]:
if abs(Kv_barnett - K_barnett) < abs(K_barnett - Kr_barnett):
  print('The ultrasonic velocity measurement (nearer to) represents the iso-strain')
if abs(Kv_barnett - K_barnett) > abs(K_barnett - Kr_barnett):
  print('The ultrasonic velocity measurement (nearer to) represents the iso-stress')

The ultrasonic velocity measurement (nearer to) represents the iso-strain


#### Based on your answer above, what orientation is reflected by the ultrasonic velocity measurements?

See figure below.

* The applied stress direction to an **iso-stress** (represents a vertical sample) is **perpendicular** to bedding. 
* The applied stress direction to an **iso-strain** (represents a horizontal sample) is **parallel** to bedding. 

![iso stress iso strain](https://user-images.githubusercontent.com/51282928/80067844-c962a680-8568-11ea-9ab7-928b41e14f09.PNG)

In [0]:
print('Because the end member is iso-strain, the ultrasonic velocity measurement is parallel to bedding')

Because the end member is iso-strain, the ultrasonic velocity measurement is parallel to bedding


### Q5. Assuming a normal faulting regime, which layer would you stimulate to achieve a wide fracture confined to only one layer?

A layer (e.g. layer X) with Shmin lower than both layers above and below it, when a fracture is propagated at layer X, will not propagate vertically

In [0]:
print('Minimum horizontal stress for layer 1:', Sh1, 'psi, layer 2:', Sh2, 'psi, layer 3:', Sh3, 'psi, layer 4:', Sh4, 'psi, and layer 5:', Sh5, 'psi')

Minimum horizontal stress for layer 1: 5150 psi, layer 2: 4500 psi, layer 3: 5000 psi, layer 4: 5050 psi, and layer 5: 6200 psi


So should be in Layer 2, because its Shmin (4500 psi) is lower than the above Layer 1 (Shmin = 5150 psi) and the underneath Layer 3 (Shmin = 5000 psi)

### Q6

#### What is the net pressure (in psi) required to propagate the fracture at l = 3 ft in Layer 3?

In [0]:
print('Net pressure for 3 ft fracture propagation in layer 3:', netpressure3_3ft, 'psi')

Net pressure for 3 ft fracture propagation in layer 3: 110.26577908435841 psi


#### What is the net pressure (in psi) required to propagate the fracture at l = 3 ft in Layer 4?

In [0]:
print('Net pressure for 3 ft fracture propagation in layer 4:', netpressure4_3ft, 'psi')

Net pressure for 3 ft fracture propagation in layer 4: 36.75525969478614 psi


#### What can be said about the relationship about rock tensile strength and hydraulic fracture propagation? Select ALL possible correct answers.



In [0]:
print('Tensile strength is not important because the net pressure to propagate a fracture is small')
print('Tensile strength is not important because reservoirs contain fractures, faults, and flaws at all scales')

Tensile strength is not important because the net pressure to propagate a fracture is small
Tensile strength is not important because reservoirs contain fractures, faults, and flaws at all scales


### Q7. 

#### If we apply sufficient pressure to propagate a hydraulic fracture of length l = 1 ft in layer 3, would we expect the fracture to grow vertically into any of the surrounding layers? Which ones? Select ALL possible correct answers.

In [0]:
print('Minimum horizontal stress for layer 1:', Sh1, 'psi, layer 2:', Sh2, 'psi, layer 3:', Sh3, 'psi, layer 4:', Sh4, 'psi, and layer 5:', Sh5, 'psi \n')

print('Net pressure for 1 ft fracture propagation in layer 1:', netpressure1_1ft, 'psi')
print('Net pressure for 1 ft fracture propagation in layer 2:', netpressure2_1ft, 'psi')
print('Net pressure for 1 ft fracture propagation in layer 3:', netpressure3_1ft, 'psi')
print('Net pressure for 1 ft fracture propagation in layer 4:', netpressure4_1ft, 'psi')
print('Net pressure for 1 ft fracture propagation in layer 5:', netpressure5_1ft, 'psi')

Minimum horizontal stress for layer 1: 5150 psi, layer 2: 4500 psi, layer 3: 5000 psi, layer 4: 5050 psi, and layer 5: 6200 psi 

Net pressure for 1 ft fracture propagation in layer 1: 159.15494309189535 psi
Net pressure for 1 ft fracture propagation in layer 2: 95.4929658551372 psi
Net pressure for 1 ft fracture propagation in layer 3: 190.9859317102744 psi
Net pressure for 1 ft fracture propagation in layer 4: 63.66197723675813 psi
Net pressure for 1 ft fracture propagation in layer 5: 127.32395447351627 psi


Quick look from the Shmin, Layer 3 has Shmin = 5000 psi. The above Layer 2 has lower Shmin = 4500 psi. So, fracture likely propagates vertically to Layer 2.

Will it propagate vertically to Layer 4. Although Shmin of Layer 4 (5050 psi) is higher than Layer 3, another criteria for propagation is the **pressure required to propagate** (not the net pressure). Pressure is defined as:

$$P=(\frac{K_{IC}}{\pi \sqrt{L}})+S3$$



In [0]:
print('Pressure required for 1 ft fracture propagation in layer 1:', netpressure1_1ft + Sh1, 'psi')
print('Pressure required for 1 ft fracture propagation in layer 2:', netpressure2_1ft + Sh2, 'psi')
print('Pressure required for 1 ft fracture propagation in layer 3:', netpressure3_1ft + Sh3, 'psi')
print('Pressure required for 1 ft fracture propagation in layer 4:', netpressure4_1ft + Sh4, 'psi')
print('Pressure required for 1 ft fracture propagation in layer 5:', netpressure5_1ft + Sh5, 'psi \n')

if (netpressure4_1ft + Sh4) > (netpressure3_1ft + Sh3):
  print('Fracture in Layer 3 CANNOT propagate to Layer 4')
if (netpressure4_1ft + Sh4) < (netpressure3_1ft + Sh3):
  print('Fracture in Layer 3 CAN propagate to Layer 4')

Pressure required for 1 ft fracture propagation in layer 1: 5309.154943091895 psi
Pressure required for 1 ft fracture propagation in layer 2: 4595.492965855137 psi
Pressure required for 1 ft fracture propagation in layer 3: 5190.985931710275 psi
Pressure required for 1 ft fracture propagation in layer 4: 5113.6619772367585 psi
Pressure required for 1 ft fracture propagation in layer 5: 6327.323954473516 psi 

Fracture in Layer 3 CAN propagate to Layer 4


So, fracture in Layer 3 can propagate to Layer 2 and Layer 4

Why? Select ALL possible correct answers.

In [0]:
print('The minimum horizontal stress in Layer 2 is less than in Layer 3')
print('The pressure required to propagate the fracture exceeds the minimum horizontal stress in Layer 4')

The minimum horizontal stress in Layer 2 is less than in Layer 3
The pressure required to propagate the fracture exceeds the minimum horizontal stress in Layer 4
